version: "3.8"

services:
  paper-app:
    build:
      context: .docker/
      dockerfile: ./Dockerfile
      target: local
    environment:
      - CONTAINER_ROLE=${CONTAINER_ROLE}
    volumes:
      - ../:/var/www/${CONTAINER_ROLE}:cached
    ports:
      - "8016:8080"
      - "5176:5176"
